### ISSUE TITLE
Base calls drop off near end of sequence even though the chromatogram is of sufficient quality

### ISSUE THREAD

**Issue by KMBarton** [roblanf/sangeranalyseR#14]
When I run make.consensus.seqs it sometimes stops calling bases toward the 3' end of the sequence even though our comparator program is able to call this sequence and the chromatogram looks to be of sufficient quality by eye. Image 1 is the fasta file of the 3' end of make.consensus.seqs contig on top and the contig from the comparator script on bottom for sample 020202_30. Image 2 is the corresponding ab1 chromatogram for the corresponding region of sequence.

![020202_30_fas_2](https://cloud.githubusercontent.com/assets/19339270/20823290/e905fb0a-b8a6-11e6-8fc2-dd192fb05503.jpg)

![020202_30_cg_2](https://cloud.githubusercontent.com/assets/19339270/20823297/f640fc70-b8a6-11e6-8936-b38c697aa498.jpg)

**Comment by roblanf** [comment]
Hi Kirston,

As with your other issues - I cannot recreate this. When I run 


```
input.folder = "/0202/0202_ab1" # this is the data you sent me
forward.suffix = "_F.ab1"
reverse.suffix = "_R.ab1"
cs = make.consensus.seqs(input.folder, forward.suffix, reverse.suffix)
```

I get a sequence for 30HT that matches extremely closely what you see for the 30HT.Contig1 in your example. I do not see any missing bases near there - I see about another 150 bases of well-called sequence that seems to align pretty nicely with all the other sequences in the data you sent me.

Two things:

1. Can you let me know exactly what you did to get to these sequences, alignments, and chromatograms, so that I can try to recreate what you did.

2. Can you try updating sangeranalyseR and all of the dependencies to see if it's just that you're using an old version.

Cheers,

Rob
