### ISSUE TITLE
writeFasta problem

### ISSUE THREAD

**Issue by phkrogh** [roblanf/sangeranalyseR#63]
The  SangerAlignment creates successfully a SangerAlignment' S4 instance but the writeFasta
reports this error
"Error in" writeXStringSet(alignmentObject, file.path(outputDir, "Sanger_contigs_alignment.fa"),  : 
  'x' must be an XStringSet object

If I use 
writeFasta(sangerAlignmentData, outputDir = "[path]")
it will write some hidden earthworm sequence example dataset 
(Achl_ACHLO007 and Achl_ACHLO040) to the three files:
Sanger_all_trimmed_reads.fa
Sanger_contigs_unalignment.fa
Sanger_contigs_alignment.fa

**Comment by Kuanhao-Chao** [comment]
Hi @phkrogh 

Could you send me your data (kuanhao.chao@gmail.com), so I can check it for you?
By your description, it seems to me that you may use the wrong input for `writeFasta ` function. 
The input for `writeFasta ` function is the SangerAlignment S4 instance that you created in the previous step. 

And for the example dataset in sangeranalyseR, can you successfully create those three FASTA file that you listed?  Thanks a lot!

cheers,

Howard

**Comment by Kuanhao-Chao** [comment]
Hi @phkrogh 

Thanks for your email. I've checked your code and fixed the problem. 
The reason why your program crashed is because your created sangerAlignment instance only contains one contig; therefore, the `contigsAlignment` is NULL in the sangerAlignment instance and can not be written out as a FASTA file. 

I have fixed this issue in the latest commit. sangeranalyseR now generates a warning instead of stopping the program. 
And if you want to check your alignment result, you can run the following code:

`BrowseSeqs(scurv@contigList[1]$`180217-011`@alignment)`
<img width="1417" alt="Screen Shot 2020-11-03 at 1 57 25 am" src="https://user-images.githubusercontent.com/26069376/97902017-ee39a100-1d77-11eb-9b61-cbfb7ca48ec1.png">

Thanks for the bug report!

cheers,

Howard
