### ISSUE TITLE
Is there a version in R 3.6 that I can install?

### ISSUE THREAD

**Issue by lixiaopi1985** [roblanf/sangeranalyseR#64]
Hi,

I thought I could update the package so I deleted the package, but later found out the newest version is on R 4.0. Is there a lower version that I can download and install?

Thanks,

**Comment by Kuanhao-Chao** [comment]
Hi @lixiaopi1985,

sangeranalyseR is only maintained in R 4.0.0 environment because it is a Bioconductor 3.12 Release package (The R version of all packages in Bioconductor 3.12 Release must be at least 4.0.0).

But there is still a way to install sangeranalyseR in lower R version. The following are the steps.  
1. Install the source code through GitHub locally. 
2. Decompress the source code. 
3. Open the `DESCRIPTION` file, and find the following code
* Before
```
Depends: 
    R (>= 4.0.0),
```
* After
```
Depends: 
    R ,
```
4. Compress the source code directory.
5. Install the R package through 
```
library(devtools)
install_local("./sangeranalyseR.zip")
```

Hope it works for you. But I highly recommend you to install another R 4.0.0 version to run sangeranalyseR.

Howard
