### ISSUE TITLE
color in chromatogram

### ISSUE THREAD

**Issue by Andreas-Bio** [roblanf/sangeranalyseR#83]
![image](https://user-images.githubusercontent.com/19622117/176560016-55639465-146d-412f-9cb0-f1ca721ed88d.png)

Not the same as trace?

**Comment by Kuanhao-Chao** [comment]
Hi @andzandz11 ,

Sorry to get back to you late. Since the package that sangeranalyseR depends on, sangereqR, changed its color coding for the previous release, so that's why the colors of the sequences do not match with the chromatogram. Thank you for pointing out this bug : )

I've fixed it in the latest version of sangeranalyseR. Please try the newest version and see if it works for you

```
install.packages("devtools")

library(devtools)
install_github("roblanf/sangeranalyseR", ref = "develop")
library(sangeranalyseR)
```

Best wishes,
Kuan-Hao
