### ISSUE TITLE
Error: unable to find an inherited method for function

### ISSUE THREAD

**Issue by EunokLee** [roblanf/sangeranalyseR#9]
Hi Rob, 

I was trying to do reverse complement part but I have an error:

Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘reverseComplement’ for signature ‘"sangerseq"’

How should I solve this error?

Thank you!

-Eunok

**Comment by roblanf** [comment]
Hi Eunok,

This is not really an issue with sangeranalyseR. 

What you need to do here (and in general whenever you get an error trying to run a function) is to look at the documentation for that function, like so:

```
?reverseComplement
```

In this case, you will see that the function takes an object 'x', which it says must be 'A DNAString, RNAString, DNAStringSet, RNAStringSet, XStringViews (with DNAString or RNAString subject), MaskedDNAString or MaskedRNAString object for complement and reverseComplement.'

So the issue here is that you are sending it something it cannot work with. You will need to convert your sequence to one of the valid objects for it to work. To convert to a DNAstring, you will need to use the `DNAString` function. As before, you can see how to use it with `?DNAString`.

Cheers,

Rob

**Comment by EunokLee** [comment]
Thank you!

It worked :)
